# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('attractionsID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(blank=True, max_length=14, null=True)),
                ('hours', models.CharField(blank=True, max_length=28, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('streetName', models.CharField(blank=True, max_length=40, null=True)),
                ('stateInfo', models.CharField(blank=True, max_length=40, null=True)),
                ('googleMaps', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(blank=True, max_length=14, null=True)),
                ('hours', models.CharField(blank=True, max_length=28, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('streetName', models.CharField(blank=True, max_length=40, null=True)),
                ('stateInfo', models.CharField(blank=True, max_length=40, null=True)),
                ('googleMaps', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('schoolID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(blank=True, max_length=14, null=True)),
                ('hours', models.CharField(blank=True, max_length=28, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.IntegerField(choices=[('2', 'Elementary'), ('1', 'Preschool'), ('3', 'Middle & High')], default=1)),
                ('streetName', models.CharField(blank=True, max_length=40, null=True)),
                ('stateInfo', models.CharField(blank=True, max_length=40, null=True)),
                ('googleMaps', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Important',
            fields=[
                ('importantID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(blank=True, max_length=14, null=True)),
                ('hours', models.CharField(blank=True, max_length=28, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.IntegerField(choices=[('3', 'State Offices'), ('2', 'County Supervisors'), ('4', 'Federal Offices'), ('6', 'Job Services'), ('5', 'Emergency Services'), ('1', 'Mohave County Offices')], default=1)),
                ('streetName', models.CharField(blank=True, max_length=40, null=True)),
                ('stateInfo', models.CharField(blank=True, max_length=40, null=True)),
                ('googleMaps', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(blank=True, max_length=14, null=True)),
                ('hours', models.CharField(blank=True, max_length=28, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('streetName', models.CharField(blank=True, max_length=40, null=True)),
                ('stateInfo', models.CharField(blank=True, max_length=40, null=True)),
                ('googleMaps', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('utilityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(blank=True, max_length=14, null=True)),
                ('hours', models.CharField(blank=True, max_length=28, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.IntegerField(choices=[(6, 'Cable Service Providers'), (2, 'Propane'), (3, 'Water, Sewer, and Trash'), (4, 'Telephone'), (1, 'Electric and Gas'), (5, 'Internet Service Providers')], default=1)),
                ('streetName', models.CharField(blank=True, max_length=40, null=True)),
                ('stateInfo', models.CharField(blank=True, max_length=40, null=True)),
                ('googleMaps', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
    ]
