# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20170716_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgeCampRV',
            fields=[
                ('LCRVID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(blank=True, max_length=14, null=True)),
                ('hours', models.CharField(blank=True, max_length=28, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('streetName', models.CharField(blank=True, max_length=40, null=True)),
                ('stateInfo', models.CharField(blank=True, max_length=40, null=True)),
                ('googleMaps', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
    ]
